# Generated by Django 4.0.3 on 2023-01-17 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Short description of suggestion', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Explaination of why this is an improvement or great idea', null=True)),
                ('post_anonymous', models.BooleanField(default=False, help_text="Don't display your name in the list of suggestions")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('wont-do', "Won't do"), ('approved', 'Approved'), ('implemented', 'Implemented'), ('under-consideration', 'Under consideration')], default='pending', max_length=50)),
                ('vote_status', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
                ('down_votes', models.ManyToManyField(blank=True, related_name='down_votes', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('up_votes', models.ManyToManyField(blank=True, related_name='up_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'ordering': ['-created'],
            },
        ),
    ]
