[flake8]
max_line_length = 160

[tool.isort]
profile = "black"

[tool.black]
line-length = 160
include = '\\.pyi?$'
exclude = '''
/(
    \\.git
  | \\.hg
  | \\.mypy_cache
  | \\.tox
  | \\.venv
  | _build
  | buck-out
  | build
  | dist
  |
)/
'''
